image: registry.gitlab.com/tiagocoutinho/tango-conda-recipes:build

before_script:
  - source /opt/conda/bin/activate

build:
  stage: build
  script:
    - cd tango
    - conda build -b --output-folder=../dist/ .
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - anaconda upload --channel=tango-controls --token=$ANACONDA_TOKEN dist/linux-64/*.tar.bz2
  only:
    - master
