image: registry.gitlab.com/tiagocoutinho/tango-conda-recipes:build

before_script:
  - source /opt/conda/bin/activate

build:
  stage: build
  script:
    - cd tango
    - conda build --output-folder=../dist/ .
  artifacts:
    paths:
      - dist/
  except:
    - master

deploy:
  stage: deploy
  script:
    - cd tango
    - conda build --token $ANACONDA_TOKEN --output-folder=../dist/ .
  artifacts:
    paths:
      - dist/
  only:
    - master