image: registry.gitlab.com/tiagocoutinho/tango-conda-recipes:build

before_script:
  - source /opt/conda/bin/activate

build:
  stage: build
  script:
    - cd tango
    - conda build -b --output-folder=../dist/ .
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - anaconda -t $ANACONDA_TOKEN upload dist/linux-64/*.tar.bz2
  only:
    - master
