before_script:
  - source /opt/conda/bin/activate

build:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - conda build . --output-folder=../dist/ --channel=file://conda
  artifacts:
    paths:
      - dist/
  except:
    - master

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - mv -f dist/linux-64/* /conda/linux-64/
    - conda index /conda/linux-64/
  except:
    - master