image: registry.gitlab.com/tiagocoutinho/tango-conda-recipes:build

before_script:
  - echo "Updating CI tool"
  - conda install -qy -c msarahan conda-gitlab-ci
  - conda update -qy -c msarahan conda-gitlab-ci

determine_builds:
  script:
    - cgci .

build_only:
  script:
    - if [ -n "$BUILD_RECIPE" ]; then conda build -b --prefix-length=80 $TEST_MODE $BUILD_RECIPE -c tango-controls
  except:
    - master

deploy:
  script:
    - if [ -n "$BUILD_RECIPE" ]; then conda build --prefix-length=80 --token $ANACONDA_TOKEN $TEST_MODE $BUILD_RECIPE -c tango-controls
  only:
    - master
