before_script:
  - source /opt/conda/bin/activate

build:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - conda build . --output-folder=../dist/
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - mv -f dist/linux-64/*.tar.bz2 /conda/linux-64/
    - conda index /conda/linux-64/
  only:
    - master
