{% set version = "9.3.2-alpha.1" %}

package:
  name: tango
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/tango-cs/files/tango-{{ version }}.tar.gz
  url: https://github.com/tango-controls/TangoSourceDistribution/releases/download/{{ version }}/tango-{{ version }}.tar.gz
requirements:
  build:
    - libtool
    - {{ compiler('cxx') }}
  host:
    - omniorb
    - zeromq
    - zlib
  run:
    - {{ pin_compatible('omniorb') }}
    - {{ pin_compatible('zeromq') }}

about:
  home: http://www.tango-controls.org
  license: GPL2
  license_file: COPYING
  summary: A software toolkit for building control systems
